#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Worker\Command\ConsumeCountryQueueCommand;
use Worker\Command\ConsumeCapitalQueueCommand;

$application = new Application();

// Register your commands
$application->add(new ConsumeCountryQueueCommand());
$application->add(new ConsumeCapitalQueueCommand());

$application->run();
