
version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15673:15672"
      - "5672:5672"
