name: PHP Project with RabbitMQ

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --hostname rabbitmq
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml # Add other pre-compiled extensions here
          tools: pecl

      - name: Install raphf extension (if not pre-compiled)
        run: |
          sudo pecl channel-update pecl.php.net
          echo | sudo pecl install raphf

      - name: Install propro extension (if not pre-compiled)
        run: |
          echo | sudo pecl install propro

      - name: Enable extensions manually if not auto-enabled by pecl
        run: |
          echo "extension=raphf.so" | sudo tee -a /etc/php/8.2/cli/conf.d/30-raphf.ini
          echo "extension=propro.so" | sudo tee -a /etc/php/8.2/cli/conf.d/30-propro.ini

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Here you might want to configure RabbitMQ, e.g., creating specific queues/exchanges
      # - name: Prepare RabbitMQ
      #   run: |
      #     # Use rabbitmqadmin or similar tools to configure RabbitMQ
      #     # Example: rabbitmqadmin declare queue name=my_queue durable=true

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

    # Additional steps for your workflow (coding standards checks, static analysis, etc.) can be added here
