name: PHP Project with RabbitMQ

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml # Add other necessary extensions
          tools: pecl

      - name: Install and Enable Extensions
        run: |
          sudo pecl install raphf || echo "Skipping raphf installation."
          sudo pecl install propro || echo "Skipping propro installation."
          if [ -f "$(pecl config-get ext_dir)/raphf.so" ]; then
            echo "extension=raphf.so" | sudo tee -a "$(php -r 'echo php_ini_loaded_file();')"
          fi
          if [ -f "$(pecl config-get ext_dir)/propro.so" ]; then
            echo "extension=propro.so" | sudo tee -a "$(php -r 'echo php_ini_loaded_file();')"
          fi

      - name: Verify PHP and extensions
        run: |
          php -v
          php -m
          pecl list

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --hostname rabbitmq
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

    # Additional steps for your workflow (coding standards checks, static analysis, etc.) can be added here
